### ISSUE TITLE
BUG: upgrade from 2.3.1 to 2.4.0 breaks no_std build

### ISSUE THREAD

**Issue by antimora** [starkat99/half-rs#107]
We use `half` lib extensively in our Burn project and we have a git action to build for no_std which is [failing when upgrading from 2.3.1 to 2.4.0](https://github.com/tracel-ai/burn/pull/1364).

I recommend CI step is added specifically to test `std` feature off (no_std testing) because a similar problem occurred in the past (see https://github.com/starkat99/half-rs/issues/84). 

See errors:

```
Compiling bincode v2.0.0-rc.3
  error: cannot find macro `vec` in this scope
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.4.0/src/slice.rs:368:23
      |
  368 |         let mut vec = vec![0f32; self.len()];
      |                       ^^^
      |
  help: consider importing this macro
      |
  10  + use alloc::vec;
      |
  
  error: cannot find macro `vec` in this scope
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.4.0/src/slice.rs:377:23
      |
  377 |         let mut vec = vec![0f64; self.len()];
      |                       ^^^
      |
  help: consider importing this macro
      |
  10  + use alloc::vec;
      |
  
  error: cannot find macro `vec` in this scope
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.4.0/src/slice.rs:462:23
      |
  462 |         let mut vec = vec![0f32; self.len()];
      |                       ^^^
      |
  help: consider importing this macro
      |
  10  + use alloc::vec;
      |
  
  error: cannot find macro `vec` in this scope
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.4.0/src/slice.rs:471:23
      |
  471 |         let mut vec = vec![0f64; self.len()];
      |                       ^^^
      |
  help: consider importing this macro
      |
  10  + use alloc::vec;
      |
  
  error: cannot find macro `vec` in this scope
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.4.0/src/vec.rs:139:23
      |
  139 |         let mut vec = vec![f16::from_bits(0); slice.len()];
      |                       ^^^
      |
  help: consider importing this macro
      |
  12  + use alloc::vec;
      |
  
  error: cannot find macro `vec` in this scope
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.4.0/src/vec.rs:146:23
      |
  146 |         let mut vec = vec![f16::from_bits(0); slice.len()];
      |                       ^^^
      |
  help: consider importing this macro
      |
  12  + use alloc::vec;
      |
  
  error: cannot find macro `vec` in this scope
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.4.0/src/vec.rs:[175](https://github.com/tracel-ai/burn/actions/runs/8042757366/job/21963835704?pr=1364#step:11:178):23
      |
  175 |         let mut vec = vec![bf16::from_bits(0); slice.len()];
      |                       ^^^
      |
  help: consider importing this macro
      |
  12  + use alloc::vec;
      |
  
  error: cannot find macro `vec` in this scope
     --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.4.0/src/vec.rs:[182](https://github.com/tracel-ai/burn/actions/runs/8042757366/job/21963835704?pr=1364#step:11:185):23
      |
  182 |         let mut vec = vec![bf16::from_bits(0); slice.len()];
      |                       ^^^
      |
  help: consider importing this macro
      |
  12  + use alloc::vec;
      |
```

**Comment by antimora** [comment]
Hi @starkat99, did you get a chance to see this bug?

**Comment by starkat99** [comment]
Apologies for delay, March has been _a lot_. `no_std` is being tested in CI, but this appears to be `no_std` + `alloc` feature, which looks like is being missed in CI. Putting in a fix and CI test

**Comment by starkat99** [comment]
Released 2.4.1 with fix for this @antimora
